Rename all depending files
eclipse-esmf/esmf-sdk-js-aspect-model-loader pull request #4
Opened 2023-03-07 15:08 UTC by michelu89

This PR renames all occurrences of the Open Manufacturing Platform (OMP), Semantic Data Structuring (SDS) working group and BAMM Aspect Meta Model (BAMM) to Eclipse Semantic Modeling Framework (ESMF) and Semantic Aspect Meta Model (SAMM), respectively.

2023-03-16 12:46 UTC, atextor requested changes

2023-03-16 12:46 UTC, atextor commented on CONTRIBUTING.md
This file still contains references to Open Manufacturing Platform, OMP and/or SDS. Please update.

2023-03-16 12:46 UTC, atextor commented on test/models/events-model.ts
> +@prefix : <urn:samm:org.eclipse.esmf.samm:1.0.0#>.
The `org.eclipse.esmf.samm` namespace is reserved for the meta model and is _not_ to be used for regular models or test models. Use `org.eclipse.esmf.test` for that instead.

2023-03-20 07:44 UTC, atextor approved these changes

2023-03-20 07:46 UTC, atextor requested changes
contributing.md still needs changes

2023-03-20 08:05 UTC, michelu89 commented on CONTRIBUTING.md
Fixe

2023-03-20 09:39 UTC, atextor approved these changes

2023-03-20 10:52 UTC, merged